name: Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  tagname:
    name: 
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Fetch tags
        run: |
          git fetch --tags

      - name: Get current tag
        id: vars
        run: echo "tag=`git describe --abbrev=0 --tags`" >> "$GITHUB_OUTPUT"

      - name: test-tagname
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ steps.vars.outputs.tag }}
